name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: hami98
        password: Hamster19981226!
        registry: docker.io
        repository: hami98/hazi-feladat  
        file: ./Dockerfile

    - name: Scan image for vulnerabilities
      uses: trivy/trivy-action
      with:
        image: docker.io/hami98/hazi-feladat:latest
