name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-webapp-image -f webapp/Dockerfile .

      - name: Checks vulnerability
        run: docker run --rm -v ./workdirlocal:/workdirdocker -w /workdirdocker aquasec/trivy my-webapp-image:latest
      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Push image to Docker Hub
        run: |
            docker tag my-webapp-image hami98/hazi-feladat:latest
            docker push hami98/hazi-feladat:latest
            
    
