name: NodeJS Docker Hub pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: hami98
          password: Hamster19981226!
          repository: https://github.com/Hammer998/hazi-feladat/
          tag: latest
          working-directory: ./webapp 

    
